services:
  mongo:
    container_name: space-major-db
    image: mongo:5.0-focal
    restart: unless-stopped
    volumes:
      - type: volume
        source: space-major-data
        target: /data/db
        volume:
          nocopy: true
    ports:
      - 27017:27017

  server:
    container_name: space-major-server
    build: ./server/
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGO_URL=mongodb://mongo/space-major-dev
      - SESSION_SECRET=puritnsb89
      - SSO_CALLBACK_URL=http://localhost:3001/sso/callback
      - CLIENT_URL=http://localhost:3000
    env_file:
      - .env
    volumes:
      - ./server/src:/usr/src/app/src
    depends_on:
      - mongo

  web:
    container_name: space-major-web
    build: ./web/
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - VITE_GRAPHQL_URL=http://localhost:3001/graphql
      - VITE_SSO_LOGIN_URL=http://localhost:3001/sso/login
    volumes:
      - ./web/src:/usr/src/app/src

volumes:
  space-major-data:
