version: "3.8"

services:
  client:
    build: ./client/
    ports:
      - 3000:3000
      - 30011:30011
    container_name: space-major-client
    environment:
      - PORT=3000
      - INTERNAL_STATUS_PORT=30011
      - REACT_APP_BACKEND_URL=http://localhost:3001
      - REACT_APP_ENABLE_DEVTOOLS=true
    volumes:
      - ./client/src:/usr/src/app/src
