version: "3.8"

services:
  client:
    build: ./client/
    ports:
      - 3000:3000
      - 30011:30011
    container_name: space-major-client
    environment:
      - PORT=3000
      - INTERNAL_STATUS_PORT=30011
      - REACT_APP_BACKEND_URL=http://localhost:3001
      - REACT_APP_ENABLE_DEVTOOLS=true
    volumes:
      - ./client/src:/usr/src/app/src

  server:
    build: ./server/
    ports:
      - 3001:3001
    container_name: space-major-server
    environment:
      - NODE_ENV=development
      - PORT=3001
      - CLIENT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo/space-major
      - JWT_SECRET=asdasd
      - ENABLE_DEVTOOLS=true
    env_file:
      - .env.development
    volumes:
      - ./server/src:/usr/src/app/src

  mongo:
    image: mongo:6.0
    restart: unless-stopped
    container_name: space-major-mongo
    volumes:
      - type: volume
        source: mongo-data
        target: /data/db
        volume:
          nocopy: true
    ports:
      - 27017:27017

volumes:
  mongo-data:
